[project]
name = "autopindot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.19.0",
]
